# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """\
$directory\
$line_break\
$character"""

[directory]
truncation_length = 5
truncate_to_repo = false
style = "bold blue"

[package]
disabled = false
display_private = false

[python]
python_binary = "python3"

