#!/bin/bash

for file in ~/.shell/autoload/*; do
  eval "$(basename "$file")() { $(cat "$file"); }"
done
source ~/.shell/alias.sh

if [ -z "$TMUX" ] && [ -n "$SSH_CLIENT" ]; then
  case $- in
    *i*) print_welcome; tmux attach || mx tmux ;;
  esac
fi
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
